---
permalink: administration/reference_post_commands.html 
sidebar: sidebar 
keywords: snap, creator, server, configuration, post, command, quiescecmde, cmd, ntap, app, post, transfer 
summary: Snap Creator Server enthält mehrere Befehle FÜR DIE ERSTELLUNG von Konfigurationsdateien. 
---
= POST-Befehle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Server enthält mehrere Befehle FÜR DIE ERSTELLUNG von Konfigurationsdateien.

|===
| Befehl | Beschreibung 


 a| 
POST_APP_ QUIESCECMD ##
 a| 
Dies ist ein Befehl zum Starten des Backups nach der Anwendung, wobei ## eine Zahl von 01-99 ist.



 a| 
POST_NTAP_CMD ##
 a| 
Dies ist ein Post-Befehl, wobei ## eine Zahl von 01-99 ist. Dieser Vorgang wird ausgeführt, nachdem alle Vorgänge abgeschlossen sind.



 a| 
POST_APP_UNQUIESCE_CMD ##
 a| 
Dies ist ein Befehl zum Beenden von Backups nach der Anwendung, wobei ## eine Nummer von 01-99 ist.



 a| 
POST_NTAP_DATA_ TRANSFER_CMD ##
 a| 
Dies ist ein Befehl zum Datentransfer nach einem SnapVault oder SnapMirror Transfer, wobei ## eine Zahl zwischen 01 und 99 ist.



 a| 
POST_RESTORE_ CMD ##
 a| 
Dies ist ein optionaler Befehl, der ausgeführt werden kann, nachdem Sie eine interaktive Wiederherstellung abgeschlossen haben. Sie ermöglicht die Interaktion mit der wiederherzustellenden Anwendung. Nach Abschluss der Wiederherstellung möchten Sie die Anwendung möglicherweise starten. *Hinweis:* Dies wird vom MySQL-Plug-in nicht unterstützt.



 a| 
POST_CLONE_CREATE_ CMD ##
 a| 
Dies ist ein optionaler Befehl, der ausgeführt werden kann, nachdem ONTAPI Klonvorgänge ausgeführt werden, wobei ## eine Zahl von 01-99 ist. Die Befehle werden für Vorgänge wie das Mounten geklonter Dateisysteme verwendet.

|===