---
permalink: administration/reference_parameters_used_to_configure_the_client_and_server.html 
sidebar: sidebar 
keywords: parameter, snap, creator, agent, host, client, port 
summary: Sie müssen die Parameter für die Konfiguration des Snap Creator Agent Host-Clients und Snap Creator Server kennen. 
---
= Parameter für die Konfiguration des Snap Creator Agent Host-Client und Snap Creator Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Parameter für die Konfiguration des Snap Creator Agent Host-Clients und Snap Creator Server kennen.

|===
| Parameter | Einstellung | Beschreibung 


 a| 
SC_AGENT_##
 a| 
Hostname oder IP_Address:Port
 a| 
Führt Befehle oder Aufgaben auf mehreren Remote-Hosts gleichzeitig mit einer einzigen Konfiguration aus. Eine Aufgabe ist entweder ein definiertes Plug-in (Parameter APP_NAME) oder ein Befehl, der mit dem Befehl _CMD angegeben wird (z. B. NTAP_SNAPSHOT_CREATE_CMD01).

Um einen Remote-Host festzulegen, müssen Sie seinen Namen oder seine IP-Adresse gefolgt von einem Doppelpunkt und den Port eingeben, auf dem Snap Creator Agent abhört.

Beispiel: SC_AGENT_ number = IP-Adresse:Port

SC_AGENT_01=Agent-IP:Agent-Port

SC_AGENT_02=Agent-IP:Agent-Port

Auf dem Remote-Host können Sie Snap Creator Agent starten, indem Sie den Befehl <path to SCAgent_V<#>/bin/SCAgent Start ausführen.



 a| 
SC_CLONE_TARGET
 a| 
Hostname oder IP_address des Klonziels:Port
 a| 
Aktiviert Klonvorgänge.mit dem Parameter *cloneVol* mit dem {PRE



| NACH dem Parameter}_CLONE_CREATE_CMDxx können Sie die Remote-Speicherobjekte auf der Remote-Seite verwalten (z. B. Mounten oder Unmounten von Dateisystemen). Um ein Klonziel festzulegen, müssen Sie seinen Namen oder seine IP-Adresse gefolgt von einem Doppelpunkt und den Port eingeben, auf dem Snap Creator Agent abhört.  a| 
SC_AGENT_TIMEOUT
 a| 
Zeit (in Sekunden)



 a| 
Gibt die Zeitüberschreitung in Sekunden des Agent-Dienstes an. Die implementierte Client-/Server-Architektur verwendet einen Timeout-Mechanismus. Das bedeutet, dass der Server mit einer Timeout-Meldung fehlschlägt, wenn der Client nicht im angegebenen Intervall reagiert. Die Aufgabe auf dem Client wird jedoch nicht abgebrochen und erfordert weitere Untersuchungen.

Die Zeitüberschreitung ist standardmäßig auf 300 Sekunden eingestellt. Auf einem Server mit hoher Auslastung oder bekannten lang laufenden Aufgaben (z. B. von Benutzern erstellte Skripte oder komplexe SnapDrive-Vorgänge) sollten Sie das Timeout verlängern und diesen Wert entsprechend Ihren Anforderungen ändern.

Sie sollten diesen Parameter auf die maximale Zeit einstellen, die ein Vorgang durchführen kann (wenn zum Beispiel quiesce 1,800 Minuten dauert, muss dieser Parameter auf 1800 gesetzt werden).


NOTE: Einige Plug-ins haben spezifische Anforderungen für SC_AGENT_TIMEOUT.
 a| 
SC_AGENT_WATCHDOG_ENABLE
 a| 
„`Y`“ oder „`N`“



 a| 
Der Parameter SC_AGENT_WATCHDOG_ENABLE wird nur angewendet, wenn die Snap Creator Agent-Version vor 4.1 liegt. Dieser Parameter aktiviert oder deaktiviert den Watchdog-Prozess. Bei Snap Creator Agent 4.1 oder neuer wird dieser Parameter ignoriert, da der Watchdog-Prozess immer aktiviert ist. Wenn der Parameter aktiviert ist (d. h. auf Y gesetzt) und die Snap Creator Agent Version 4.1 oder höher ist, wird der Watchdog-Prozess gestartet, wenn der Snap Creator Agent eine quiesce-Anfrage erhält.

Der Watchdog-Prozess verwendet den Parameter SC_AGENT_UNQUIESCE_TIMEOUT als Timeout, um die Anwendung stillzulegen. Wenn der Parameter deaktiviert ist (d. h. auf N gesetzt) und die Snap Creator Agentversion älter als 4.1 ist, wird die Anwendung vom Watchdog-Prozess stillgelegt, er verwendet jedoch den Parameter OPERATION_TIMEOUT_IN_MS (Standard: 1 Stunde) aus dem Pfad SCAgent/etc/agent.properties.


NOTE: Der Parameter SC_AGENT_WATCHDOG_ENABLE ist mit Snap Creator Agent 4.1 veraltet und gilt nur für die Verwendung mit Snap Creator Agent 4.0. Ab Snap Creator Agent 4.1 ist der Watchdog-Prozess aktiviert (da er hartcodiert ist), unabhängig vom für diesen Parameter eingestellten Wert.
 a| 
SC_AGENT_UNQUIESCE_TIMEOUT
 a| 
Zeit (in Sekunden)



 a| 
Gibt die Zeitüberschreitung für das nicht-quiesce-Stillstand in Sekunden an. Bei Snap Creator Agent Versionen vor 4.1 wird dieser Parameter nur verwendet, wenn SC_AGENT_WATCHDOG_ENABLE auf Y. Mit Snap Creator Agent 4.1 oder neuer ist der Parameter immer anwendbar, da der Snap Creator Agent Watchdog-Prozess immer aktiviert ist.Wenn die Kommunikation mit Snap Creator Agent nicht möglich ist und eine Applikation sich im quiesce-Status befindet, Der Snap Creator Agent gibt die Anwendung automatisch ohne Kommunikation vom Server in den normalen Betriebsmodus zurück. Standardmäßig ist das unquiesce-Timeout auf den Parameterwert SC_AGENT_TIMEOUT gesetzt, plus fünf Sekunden.
 a| 
SC_TMP_DIR
 a| 
„`Y`“ oder „`N`“



 a| 
Ermöglicht die Verwendung eines benutzerdefinierten, alternativen temporären Verzeichnisses zum Speichern von Snap Creator-bezogenen Dateien. Der Benutzer erstellt das Verzeichnis und verwaltet den Benutzerzugriff. Die Plug-ins verwenden temporäre Dateien, um mit der Datenbank zu interagieren. Die temporären Dateien werden im standardmäßigen temporären Verzeichnis des Hosts erstellt, das Schreibzugriff für alle Benutzer hat. Wenn das temporäre Verzeichnis voll ist, zeigt Snap Creator beim Erstellen der temporären Dateien einen Fehler an.
 a| 
SC_AGENT_LOG_ENABLE
 a| 
„`Y`“ oder „`N`“

|===