---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: Sie können den Standard-Schlüsselspeicher oder -Zertifikat mithilfe des Keytool-Befehls anpassen, der unter Windows und UNIX verfügbar ist. 
---
= Anpassen des Standard-Keystore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Standard-Schlüsselspeicher oder -Zertifikat mithilfe des Keytool-Befehls anpassen, der unter Windows und UNIX verfügbar ist.

Der Befehl keytool wird von Java bereitgestellt. In einigen Umgebungen müssen Sie möglicherweise zum Java-Installationsverzeichnis wechseln, um den keytool-Befehl auszuführen.

Snap Creator unterstützt keine Truststores.

. Stoppen Sie den Snap Creator Agent.
. Generieren Sie einen neuen Schlüsselspeicher mit einem einzigen Zertifikat:
+
`keytool -genkeypair -alias alias_name -keystore keystore_file -keypass private_key_password -storepass keystore_password`

+
Keytool -genkeypair -alias servicekey -keystore-DiensteKeystore.jks -keypass kypswd123 -storepass kystrpswd123

. Kopieren Sie die Schlüsselspeicherdatei in das Verzeichnis scAgent4.3.0/etc/.
. Aktualisieren Sie DIE KENNWORTPARAMETER KEYSTORE_FILE=keystore_file und KEYSTORE_PASS=keystore in der Snap Creator Agent-Konfigurationsdatei (scAgent4.3.0/etc/allowed_befiehlt.config).
. Starten Sie den Snap Creator Agent.


*Verwandte Informationen*

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Starten, Überprüfen und Stoppen von Snap Creator Agent unter Windows]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[Starten, Überprüfen und Stoppen von Snap Creator Agent auf UNIX]
