---
permalink: administration/task_setting_snap_creator_server_credentials.html 
sidebar: sidebar 
keywords: snap, creator, server, credentials, scadmin, port 
summary: 'Sie können die Snap Creator Server-Anmeldeinformationen speichern (z. B. Host-Name des Servers oder IP-Adresse, Port-, Benutzer- und Passworteinstellungen), um zu vermeiden, dass die Anmeldeinformationen nicht mehrmals in die Befehlszeilenschnittstelle (CLI) eingegeben werden. Bei Bedarf können Sie die gespeicherten Anmeldeinformationen entfernen.' 
---
= Festlegen von Snap Creator Server-Anmeldeinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Snap Creator Server-Anmeldeinformationen speichern (z. B. Host-Name des Servers oder IP-Adresse, Port-, Benutzer- und Passworteinstellungen), um zu vermeiden, dass die Anmeldeinformationen nicht mehrmals in die Befehlszeilenschnittstelle (CLI) eingegeben werden. Bei Bedarf können Sie die gespeicherten Anmeldeinformationen entfernen.

Das Verfahren zum Einstellen der Snap Creator Server-Anmeldeinformationen ist für Windows und UNIX identisch. Das folgende Verfahren nutzt Beispiele aus der UNIX-Umgebung.

. Geben Sie auf dem Host, auf dem der Snap Creator Server installiert ist, den folgenden Befehl aus dem Snap Creator Server Installationsverzeichnis ein:
+
`/install_path/scServer4.3/snapcreator --credentials`

+
Die folgende Ausgabe wird angezeigt, sodass Sie die Standardanmeldeinformationen für den Snap Creator Server festlegen können:

+
[listing]
----
Enter user: SCadmin

Enter password:

Enter Snap Creator server hostname or IP [localhost]:
Enter Snap Creator server port [8443]:
Enter Profile name ( or * for any profile: *
Enter Config name ( or * for any config: *
----
. Geben Sie die entsprechenden Informationen für jeden Eintrag ein.
+
Nachdem Sie Ihre Eingabe für den Eintrag Config Name eingegeben haben, werden die Anmeldeinformationen gespeichert und die folgende Meldung angezeigt: INFO: CLI-Anmeldeinformationen erfolgreich gespeichert. Die Anmeldeinformationen werden in der Datei creator.redentials im Verzeichnis .snapcreatorverzeichnis oder im Home-Verzeichnis gespeichert.

. Wenn Sie die gespeicherten Anmeldeinformationen entfernen möchten, löschen Sie die Datei creator.Credentials.

