---
permalink: installation/task_creating_symbolic_links_for_domino_plug_in_on_aix_hosts.html 
sidebar: sidebar 
keywords: creating, create, symbolic, links, domino, plug-in, aix, hosts 
summary: Sie müssen dieses Verfahren durchführen, um symbolische Links für das Domino Plug-in auf AIX-Hosts hinzuzufügen. 
---
= Erstellen von symbolischen Links für das Domino Plug-in auf AIX-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen dieses Verfahren durchführen, um symbolische Links für das Domino Plug-in auf AIX-Hosts hinzuzufügen.

Sie sollten Befehle nicht direkt aus diesem Dokument kopieren und einfügen. Fehler (z. B. falsch übertragene Zeichen, die durch Zeilenumbrüche und harte Rückgaben verursacht werden) können dazu führen. Kopieren Sie die Befehle in einen Texteditor, überprüfen Sie die Befehle und geben Sie sie anschließend in die CLI-Konsole ein.


NOTE: Die in den folgenden Schritten bereitgestellten Pfade beziehen sich auf die 32-Bit-Systeme; 64-Bit-Systeme müssen simlinks zu /usr/lib64 anstelle von /usr/lib erstellen.

. Fügen Sie für die folgenden Dateien Links zu /usr/lib hinzu:
+
** Libxmlproc_r.a
** Libndgts_r.a
** Libnotes_r.a
** Libgsk8iccs_r.a (nur für Domino ab Version 9.0) eine typische Methode zur Erzeugung einer symbolischen Verbindung ist die Verwendung des Befehls ln:


+
ln -s /path/to/source_file /usr/lib/Linked_file

+
+ wo:

+
** -S weist das Betriebssystem an, eine symbolische Verbindung zu machen.
** /Path/to/source_file ist der Pfad zu einer der Domino-Bibliotheksdateien, einschließlich des Dateinamens.
** Linked_File ist der Name der Datei, die verknüpft wird.
+
[listing]
----
ln -s /opt/ibm/domino/notes/latest/ibmpow/libxmlproc_r.a /usr/lib/libxmlproc_r.a
ln -s /opt/ibm/domino/notes/latest/ibmpow/libndgts_r.a /usr/lib/libndgts_r.a
ln -s /opt/ibm/domino/notes/latest/ibmpow/libnotes_r.a /usr/lib/libnotes_r.a
ln -s /opt/ibm/domino/notes/latest/linux/libgsk8iccs.so /usr/lib/libgsk8iccs_r.a
----


. Überprüfen Sie den Pfad zu den in Schritt 1 aufgeführten Dateien.
+
Die Befehle in diesem Beispiel verwenden den Standardpfad für AIX, aber die Installationen können variieren.


