---
permalink: installation/task_upgrading_snap_creator_server_4_1_x_on_unix_based_systems.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 4.1.x, unix, unix-based 
summary: Sie können ein Upgrade von Snap Creator Server 4.1.x auf UNIX-basierten Systemen durchführen. 
---
= Upgrade von Snap Creator Server 4.1.x auf UNIX-basierten Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade von Snap Creator Server 4.1.x auf UNIX-basierten Systemen durchführen.

* Sie haben die Snap Creator-Prozesse angehalten, bevor Sie das Backup der Snap Creator Verzeichnisse durchführen, um sicherzustellen, dass die gesicherten Daten abgeschlossen sind.
+
Geben Sie beispielsweise die folgenden Befehle ein:

+
[listing]
----
/install_path/scServer4.1.0/bin/scServer stop
/install_path/scAgent4.1.0/bin/scAgent stop
----
* Im Unterverzeichnis Snap Creator 4.1.x Server Engine (/install_path/scServer4.1.x/Engine) haben Sie die folgenden Verzeichnisse und alle zugehörigen Unterverzeichnisse und Dateien gesichert:
+
** Snap Creator Datenbank (./SnapCreator)
** Eigenschaften von Snap Creator Server (../etc.)
** Konfigurationsdateien (./Konfigurationen)
** Logs (../logs)
** Plug-in Repository, falls aktiviert (../SnapcreatorPlugin) *Hinweis:* Sie dürfen die von Ihnen erstellten Snap Creator 4.1.x Backup-Kopien nicht löschen.




Die in den folgenden Schritten aufgeführten Pfade beziehen sich auf den Standardinstallationspfad. Die Pfadinformationen können von Ihrem Installationspfad abweichen, wenn die Standardeinstellungen nicht verwendet wurden.

Nach Abschluss des Upgrade-Vorgangs sollten Sie die folgenden Probleme berücksichtigen:

* Wenn die aktualisierte Snap Creator Datenbank einige Aufgaben mit dem Namen „`in progress`“ enthält, bleibt der Status auch nach Abschluss des Upgrades unverändert.
* Der Standardadministrator beim neuesten Snap Creator muss in Snap Creator 4.1.x ein Administrator sein
+
Wenn der 4.1.x-Benutzer kein Administrator ist, weist das Upgrade dem 4.1.x-Benutzer eine Operatorrolle zu.

+
.. Beenden Sie die Snap Creator Prozesse, wenn Sie dies noch nicht getan haben.
+
Informationen zum Stoppen der Prozesse finden Sie in den Details, die in diesem Thema bereits erwähnt wurden.

.. Installieren Sie die neueste Version von Snap Creator, starten Sie aber nicht Snap Creator Server.
+
Weitere Informationen finden Sie in den Informationen zum Installieren von Snap Creator Server unter UNIX.

.. Das gesicherte Snap Creator 4.1.x-Datenbankverzeichnis auf den neuesten Speicherort unter /install_path/scServer4.1.x/Engine/SnapCreator kopieren.
.. Kopieren Sie das gesicherte 4.1.x-Konfigurationsverzeichnis auf den neuesten Speicherort unter /install_path/scServer4.1.x/Engine/configs).
.. Kopieren Sie das Protokollverzeichnis für gesicherte 4.1.x-Protokolle auf den letzten Speicherort unter /install_path/scServer4.1.x/Engine/logs.
.. Wechseln Sie Verzeichnisse in das Unterverzeichnis der Engine im Snap Creator-Installationspfad unter /install_path/scServer4.1.x/Engine.
.. Aktualisieren Sie Snap Creator mit folgendem Befehl: java -jar snapcreator.jar -Upgrade




Starten Sie Snap Creator Server nach Abschluss des Upgrade-Prozesses, indem Sie den folgenden Befehl eingeben:

[listing]
----
/install_path/scServer4.1.x/bin/scServer start
----
Löschen Sie auch das Snap Creator 4.1.x-Installationsverzeichnis.


IMPORTANT: Löschen Sie Ihre Backup-Kopien erst, wenn Sie sich sicher sind, dass Sie das Zurücksetzen auf eine ältere Version nicht benötigen.

Sie müssen auch den Start der Snap Creator Framework GUI überprüfen, indem Sie zum lokalen Host auf dem angegebenen Port navigieren .

Sie müssen eine Verbindung über HTTPS herstellen. Andernfalls wird die Verbindung nicht automatisch zu einer HTTPS-Verbindung umgeleitet und die GUI funktioniert nicht.
