---
permalink: installation/task_installing_the_snap_creator_agent_on_unix.html 
sidebar: sidebar 
keywords: installing, install, snap, creator, agent, unix 
summary: 'Der Snap Creator Agent kann auf jeder beliebigen offenen Plattform (AIX, HP-UX, Linux und Solaris) ausgeführt werden.' 
---
= Installieren des Snap Creator Agent auf UNIX-basierten Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Snap Creator Agent kann auf jeder beliebigen offenen Plattform (AIX, HP-UX, Linux und Solaris) ausgeführt werden.

JRE 1.8 Update 72 oder höher muss installiert sein. Weitere Informationen finden Sie unter den zugehörigen Links zum Installieren von Java auf Snap Creator Servern.

Die Person, die die Installation ausführt, muss über ausreichende Zugriffsrechte und Berechtigungen verfügen.

Der Standardport für den Snap Creator Agent ist 9090. Verwenden Sie netstat oder ein ähnliches Tool, um zu überprüfen, ob der Netzwerkport (9090 oder der Port, den Sie verwenden möchten) verfügbar ist und nicht bereits verwendet wird (z. B.: `netstat -nap | grep 9090`).

Snap Creator sollte bereits heruntergeladen werden. Weitere Informationen zum Download der Snap Creator Software finden Sie unter.

Linux wird hier als Beispielplattform verwendet.

. Kopieren Sie die heruntergeladene Snap Creator tar.gz Datei an den Speicherort, an dem Sie Snap Creator Agent installieren möchten.
+

NOTE: Wenn Sie das IBM Domino Plug-in verwenden möchten, wählen Sie einen anderen Speicherort als den Domino-Datenordner aus.

+
.. Um ein Unterverzeichnis zu erstellen, geben Sie den folgenden Befehl mit dem Verzeichnisnamen ein:
+
[listing]
----
mkdir snap_creator_directory
----
+
[listing]
----
mkdir /SC_41
----
.. Kopieren Sie die Snap Creator tar.gz-Datei in das neu erstellte Verzeichnis, indem Sie den folgenden Befehl eingeben:
+
[listing]
----
cp NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
/snap_creator_directory
----
+
[listing]
----
cp NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
/SC_41
----


. Wechseln Sie in das Verzeichnis, in das sich die Snap Creator Framework .tar-Datei befindet, und extrahieren Sie die Datei, indem Sie die folgenden Befehle eingeben:
+

NOTE: Je nach UNIX-Umgebung müssen Sie möglicherweise die Datei entpacken, bevor Sie den tar-Befehl eingeben.

+
[listing]
----
cd snap_creator_directory
tar -xvf NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
----
+
** Snap_Creator_Directory ist der Speicherort, an dem Snap Creator installiert wird.
** Die Version ist die aktuelle Version des Snap Creator Softwarepakets.
** os ist das Betriebssystem.
+
[listing]
----
cd /sc_41
tar -xvf NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
----


+
Dies extrahiert sowohl die Server- als auch die Agent-Software. In der Regel ist nur Snap Creator Server konfiguriert. Die Agenten befinden sich normalerweise auf der Datenbank oder auf den Anwendungsservern, die geschützt werden sollen, wie im folgenden Beispiel gezeigt:

+
+

+
[listing]
----
NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz  scServer4.1.0
scAgent4.1.0
----
. Geben Sie die folgenden Befehle ein, und antworten Sie auf die Eingabeaufforderungen im Beispiel zum Einrichten des Snap Creator Agent.
+
[listing]
----
cd scAgent*
./snapcreator --setup
Welcome to the NetApp Snap Creator Framework release-version!
\#\#\# Installation options \#\#\#
01. NetApp Snap Creator Framework release-version Agent
Select install option (enter a number or "q" to quit): <Enter 01>

END USER LICENSE AGREEMENT
<...the EULA displays...>

Do you accept the End User License Agreement (y|n): <Enter y>

Enter Snap Creator server port [9090]: <Enter agent port>

INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scAgentrelease-version/engine/etc/agent.properties


INFO: To start scAgent please do the following:

/install_path/scAgentrelease-version/bin/scAgent start
----
. Starten Sie den Snap Creator Agent:
+
[listing]
----
/install_path/scAgentrelease-version/bin/scAgent start
----
+

NOTE: Um den Snap Creator Agent beim Start automatisch ausführen zu lassen, fügen Sie den Startbefehl einem Skript hinzu.

+
Die Schritte zur Erstellung eines Skripts unterscheiden sich leicht von dem verwendeten Betriebssystem und den Einstellungen des Systemadministrators, der den Server verwaltet. Im Allgemeinen kann der Start-Befehl für den Snap Creator Agent einer Datei hinzugefügt werden, die mit S9 beginnt (z. B. S99scAgent), die im Unterverzeichnis /path/to/rc2.d abgelegt ist. das Unterverzeichnis rc2.d befindet sich in der Regel unter /etc/, aber dies kann vom Host-Betriebssystem und der spezifischen Konfiguration des Servers abhängen. Weitere Informationen finden Sie in der Dokumentation des verwendeten Betriebssystems.

+
Die folgende Meldung wird angezeigt:

+
[listing]
----
Starting scAgent:
    Watchdog: Running
       Agent: Running
----


*Verwandte Informationen*

xref:task_installing_java_on_snap_creator_hosts.adoc[Installieren von Java auf Snap Creator Hosts]

xref:task_downloading_the_snap_creator_software.adoc[Herunterladen der Snap Creator Software]
