---
permalink: installation/task_creating_symbolic_links_for_domino_plug_in_on_linux_and_solaris_hosts.html 
sidebar: sidebar 
keywords: creating, create, symbolic, links, domino, plug-in, linux, solaris, hosts 
summary: Sie müssen dieses Verfahren durchführen, wenn Sie symbolische Links für das Domino Plug-in unter Linux- und Solaris-Hosts erstellen möchten. 
---
= Erstellen von symbolischen Links für das Domino Plug-in unter Linux- und Solaris-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen dieses Verfahren durchführen, wenn Sie symbolische Links für das Domino Plug-in unter Linux- und Solaris-Hosts erstellen möchten.

Sie sollten Befehle nicht direkt aus diesem Dokument kopieren und einfügen. Fehler (z. B. falsch übertragene Zeichen, die durch Zeilenumbrüche und harte Rückgaben verursacht werden) können dazu führen. Kopieren Sie die Befehle in einen Texteditor, überprüfen Sie die Befehle und geben Sie sie anschließend in die CLI-Konsole ein.


NOTE: Die in den folgenden Schritten bereitgestellten Pfade beziehen sich auf die 32-Bit-Systeme; 64-Bit-Systeme müssen simlinks zu /usr/lib64 anstelle von /usr/lib erstellen.

. Fügen Sie für die folgenden Dateien Links zu /usr/lib hinzu:
+
** Libxmlproc.so
** Libndgts.so
** Libnotes.so
** Libgsk8iccs.so (nur für Domino ab Version 9.0) eine typische Methode zum Erstellen eines symbolischen Links ist die Verwendung des ln-Befehls:


+
ln -s /path/to/source_file /usr/lib/Linked_file

+
+ wo:

+
** -S weist das Betriebssystem an, eine symbolische Verbindung zu machen.
** /Path/to/source_file ist der Pfad zu einer der Domino-Bibliotheksdateien, einschließlich des Dateinamens.
** Linked_File ist der Name der Datei, die verknüpft wird.
+
[listing]
----
ln -s /opt/ibm/domino/notes/latest/linux/libxmlproc.so /usr/lib/libxmlproc.so
ln -s /opt/ibm/domino/notes/latest/linux/libndgts.so /usr/lib/libndgts.so
ln -s /opt/ibm/domino/notes/latest/linux/libnotes.so /usr/lib/libnotes.so
ln -s /opt/ibm/domino/notes/latest/linux/libgsk8iccs.so /usr/lib/libgsk8iccs.so
----


. Überprüfen Sie den Pfad zu den in Schritt 1 aufgeführten Dateien.

