---
permalink: installation/task_upgrading_the_snap_creator_server_3_6_x_on_unix.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 3.6.x, unix, unix-based 
summary: Sie können ein Upgrade direkt vom Snap Creator Server 3.6.x auf UNIX-basierten Systemen durchführen. 
---
= Aktualisieren des Snap Creator Servers 3.6.x auf UNIX-basierten Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade direkt vom Snap Creator Server 3.6.x auf UNIX-basierten Systemen durchführen.

* Wenn Sie Benutzernamen haben, die Sonderzeichen in Snap Creator enthalten, müssen Sie diese Benutzer nur mit alphabetischen Zeichen (a-z, A-Z) umbenannt haben, bevor Sie das Upgrade durchführen.
* Sie haben die Snap Creator Prozesse angehalten, bevor Sie das Backup der Snap Creator Verzeichnisse durchführen, um sicherzustellen, dass die gesicherten Daten abgeschlossen sind.
+
Geben Sie beispielsweise die folgenden Befehle ein:

+
[listing]
----
/install_path/scServer3.6.x/bin/scServer stop
/install_path/scAgent3.6.x/bin/scAgent stop
----
* Sie haben die folgenden Verzeichnisse und alle zugehörigen Unterverzeichnisse und Dateien im Snap Creator 3.6.x Server-Verzeichnis (/install_PATH/scServer3.6.x) gesichert:
+
** Snap Creator Datenbank (./gui/SnapCreator)
** Profile und Konfigurationsdateien (../Konfigurationen)
** Logs (../logs) *Hinweis:* Löschen Sie die Snap Creator 3.6.x Sicherungskopien nicht, die Sie erstellt haben.




Die in den folgenden Schritten aufgeführten Pfade beziehen sich auf den Standardinstallationspfad. Der Pfad in den unten aufgeführten Befehlen kann von Ihrem Installationspfad abweichen.

Berücksichtigen Sie nach Abschluss des Upgrade-Vorgangs die folgenden Probleme:

* Wenn die aktualisierte Snap Creator Datenbank einige Aufgaben mit dem Namen „`in progress`“ enthält, bleibt der Status auch nach Abschluss des Upgrades unverändert.
* Der Standardadministrator beim neuesten Snap Creator muss in Snap Creator 3.6.x ein Administrator sein Wenn der 3.6.x-Benutzer kein Administrator ist, weist das Upgrade dem 3.6.x-Benutzer eine Operatorrolle zu.
+
.. Beenden Sie die Snap Creator Prozesse, wenn Sie dies noch nicht getan haben.
+
Informationen zum Stoppen der Prozesse finden Sie in den Details, die weiter oben in diesem Thema angegeben sind.

.. Installieren Sie den neuesten Snap Creator, starten Sie aber nicht den Snap Creator Server Service.
+
Weitere Informationen finden Sie unter Informationen zum Installieren von Snap Creator Server unter UNIX.

.. Das gesicherte Snap Creator 3.6.x-Datenbankverzeichnis auf den aktuellen Speicherort der Datenbank kopieren (/install_path/scServer4.1.x/Engine/SnapCreator).
.. Kopieren Sie die gesicherten Snap Creator 3.6.x Profile und den Konfigurationsordner auf den neuesten Speicherort (/install_path/scServer4.1.x/Engine/configs).
.. Kopieren Sie den gesicherten Ordner Snap Creator 3.6.x logs auf den letzten Speicherort (/install_path/scServer4.1.x/Engine/logs).
.. Wechseln Sie im Snap Creator-Installationspfad in das Unterverzeichnis der Engine (/install_path/scServer4.1.x/Engine).
.. Aktualisieren Sie Snap Creator mit folgendem Befehl: java -jar snapcreator.jar -Upgrade




Starten Sie nach Abschluss des Upgrade-Prozesses den Snap Creator Server Service, indem Sie den folgenden Befehl eingeben:

/Install_PATH/scServer4.1.x/bin/scServer wird gestartet

Löschen Sie auch das Snap Creator 3.6.x Installationsverzeichnis.


IMPORTANT: Löschen Sie Ihre Backup-Kopien erst, wenn Sie sicher sind, dass Sie nicht auf eine ältere Version zurücksetzen müssen.

Sie müssen auch den Start der Snap Creator Framework GUI überprüfen, indem Sie zum lokalen Host auf dem angegebenen Port navigieren .

Sie müssen eine Verbindung über HTTPS herstellen. Andernfalls wird die Verbindung nicht automatisch zu einer HTTPS-Verbindung umgeleitet und die GUI funktioniert nicht.

*Verwandte Informationen*

xref:task_installing_the_snap_creator_server_on_unix.adoc[Installation von Snap Creator Server auf UNIX-basierten Systemen]
