---
permalink: installation/task_upgrading_the_snap_creator_server_4_0_x_on_windows.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 4.0.x, windows 
summary: Sie können ein Upgrade direkt von Snap Creator Server 4.0.x auf Windows durchführen. 
---
= Aktualisieren von Snap Creator Server 4.0.x auf Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade direkt von Snap Creator Server 4.0.x auf Windows durchführen.

* Wenn Sie Benutzernamen haben, die Sonderzeichen in Snap Creator enthalten, müssen Sie diese Benutzer nur durch alphabetische Zeichen (a bis z und A bis Z) umbenannt haben.
* Sie müssen Snap Creator Services angehalten haben (`snapcreatorserverservice` Und `snapcreatoragentservice`) Vor der Sicherung der Snap Creator Verzeichnisse, um sicherzustellen, dass die gesicherten Daten abgeschlossen sind.
+
Sie können beispielsweise das Service Snap-in verwenden, um die Dienste zu beenden:

+
.. Wählen Sie *Start* > *Lauf* und geben Sie ein `services.msc`.
.. Suchen Sie den Snap Creator Service, und wählen Sie diesen aus. Beenden Sie den Service. Alternativ können Sie eine Eingabeaufforderung öffnen und die folgenden Befehle eingeben:


+
[listing]
----
sc stop snapcreatorserverservice
sc stop snapcreatoragentservice
----
* Sie müssen die folgenden Verzeichnisse und alle zugehörigen Unterverzeichnisse und Dateien gesichert haben, müssen im Unterverzeichnis der Snap Creator 4.0.x Server Engine (C:\Programme\NetApp\Snap_Creator_Framework\scServer4.0.x\Engine) gesichert werden:
+
** Snap Creator Datenbank (..\SnapCreator)
** Eigenschaften von Snap Creator Server (..\usw.)
** Profile und Konfiguration (..\Konfigurationen)
** Logs (..\logs) *Hinweis:* die von Ihnen erstellten Sicherungskopien von Snap Creator 4.0.x dürfen nicht gelöscht werden.


* (Optional) Wenn der Snap Creator Agent auf dem gleichen Host installiert ist wie der Snap Creator Server, sollten Sie bereits die Datei Agent.conf gesichert haben (C:\Programme\NetApp\Snap_Creator_Framework\scAgent4.0.x\config\Agent.conf).


Die in den folgenden Schritten aufgeführten Pfade beziehen sich auf den Standardinstallationspfad für Windows. Die Pfadinformationen können von Ihrem Installationspfad abweichen, wenn die Standardeinstellungen nicht verwendet wurden.

Berücksichtigen Sie nach Abschluss des Upgrade-Vorgangs die folgenden Probleme:

* Wenn die aktualisierte Snap Creator Datenbank einige Aufgaben mit dem Namen „`in progress`“ enthält, bleibt der Status auch nach Abschluss des Upgrades unverändert.
* Der Standardadministrator beim neuesten Snap Creator muss in Snap Creator 4.0.x ein Administrator sein Wenn der 4.0.x-Benutzer kein Administrator ist, weist das Upgrade dem 4.0.x-Benutzer eine Operatorrolle zu.
+
.. Stoppen Sie die Snap Creator Services, wenn Sie dies noch nicht getan haben.
+
Informationen zum Anhalten der Dienste finden Sie in den Details, die weiter oben in diesem Thema angegeben wurden.

.. Deinstallieren Sie Snap Creator (für Windows), indem Sie *Start* > *Programme* > *Snap Creator* > *NetApp Snap Creator Framework deinstallieren* wählen.
+
Weitere Informationen finden Sie in den Informationen zur Deinstallation von Snap Creator unter Windows.

.. Installieren Sie den aktuellen Snap Creator Server.
+
Weitere Informationen finden Sie in den Informationen zur Installation von Snap Creator Server unter Windows.

.. Wenn Sie bei der Installation des neuesten Snap Creator Servers ausgewählt haben, den Snap Creator Server als Dienst zu starten, beenden Sie den Service.
+
Informationen zum Anhalten des Dienstes finden Sie in den Details, die weiter oben in diesem Thema angegeben sind.

.. Löschen Sie den aktuellen Snap Creator Server Datenbankordner (C:\Programme\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine\SnapCreator).
.. Das gesicherte Snap Creator 4.0.x Datenbankverzeichnis auf den neuesten Speicherort kopieren (C:\Programme\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine\SnapCreator).
.. Kopieren Sie die gesicherten Snap Creator 4.0.x Profile und das Konfigurationsverzeichnis auf den neuesten Speicherort (C:\Programme\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine\configs).
.. Das gesicherte Snap Creator 4.0.x Protokollverzeichnis kann auf den neuesten Speicherort kopiert werden (C:\Programme\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine\Logs).
.. Öffnen Sie eine Eingabeaufforderung und ändern Sie das Verzeichnis in das Unterverzeichnis der Engine im Snap Creator-Installationspfad (C:\Programme\NetApp\Snap_Creator_Framework\scServer4.1.x\Engine).
.. Aktualisieren Sie Snap Creator mit folgendem Befehl: java -jar snapcreator.jar -Upgrade




Starten Sie nach Abschluss des Upgrade-Prozesses den Snap Creator Server Service, indem Sie einen der folgenden Schritte durchführen:

* Verwenden Sie das Service-Snap-in, und starten Sie den Dienst.
* Geben Sie an einer Eingabeaufforderung den folgenden Befehl ein: `sc start snapcreatorserverservice`


Sie müssen außerdem den Start der Snap Creator Framework GUI überprüfen, indem Sie zum lokalen Host am angegebenen Port navigieren (https://IP_address:gui_port)[].

Sie müssen eine Verbindung über HTTPS herstellen. Andernfalls wird die Verbindung nicht automatisch zu einer HTTPS-Verbindung umgeleitet und die GUI funktioniert nicht.

*Verwandte Informationen*

xref:concept_installing_the_snap_creator_server.adoc[Installieren des Snap Creator Servers]

xref:task_uninstalling_snap_creator_on_windows.adoc[Deinstallieren von Snap Creator unter Windows]
