---
permalink: domino-ops/concept_preparing_for_ibm_domino_backup_and_restore_operations.html 
sidebar: sidebar 
keywords: domino, ibm, preparing, prepare, ibm, domino, backup, restore 
summary: Stellen Sie vor der Implementierung des IBM Domino Plug-ins sicher, dass Ihr Storage-System und die Hosts die Mindestanforderungen für die Ressourcen erfüllen. Sie müssen auch Storage-System-Layouts für Datenbanken konfigurieren und optional SnapMirror und SnapVault Beziehungen einrichten. 
---
= Vorbereitung auf Backup und Restore von IBM Domino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie vor der Implementierung des IBM Domino Plug-ins sicher, dass Ihr Storage-System und die Hosts die Mindestanforderungen für die Ressourcen erfüllen. Sie müssen auch Storage-System-Layouts für Datenbanken konfigurieren und optional SnapMirror und SnapVault Beziehungen einrichten.

Informationen zu Installationsanforderungen für Snap Creator Server und Agent finden Sie im https://library.netapp.com/ecm/ecm_download_file/ECMP12395424["Snap Creator Framework 4.1.2 – Installationshandbuch"]. Achten Sie besonders auf die Anforderungen vor der Installation von IBM Domino für den Agent-Host:

* Auf UNIX-Hosts müssen Sie symbolische Links zu gemeinsam genutzten Objektdateien von IBM Domino erstellen.
* Unter Windows Hosts müssen Sie den IBM Domino-Installationspfad zur PFADUMGEBVARIABLE hinzufügen.

